/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author ilham-07010
 */
public class TambahData extends javax.swing.JFrame {
    
    public String username,password,nama,status;
    public int ipa,ips,indo;
    
    public TambahData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        nilaiIpa = new javax.swing.JLabel();
        fieldIpa = new javax.swing.JTextField();
        fieldIps = new javax.swing.JTextField();
        nilaiIps = new javax.swing.JLabel();
        nilaiIndo = new javax.swing.JLabel();
        fieldIndo = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        Nama = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Username.setText("Username");

        Password.setText("Password");

        nilaiIpa.setText("Nilai IPA");

        fieldIpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldIpaKeyTyped(evt);
            }
        });

        fieldIps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIpsActionPerformed(evt);
            }
        });
        fieldIps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldIpsKeyTyped(evt);
            }
        });

        nilaiIps.setText("Nilai IPS");

        nilaiIndo.setText("Nilai Bhs. Indonesia");

        fieldIndo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldIndoKeyTyped(evt);
            }
        });

        btnTambah.setText("Tambahkan");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        Nama.setText("Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambah)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nilaiIpa)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nilaiIndo)
                        .addGap(18, 18, 18)
                        .addComponent(fieldIndo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password)
                            .addComponent(Username)
                            .addComponent(Nama)
                            .addComponent(nilaiIps))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldIps, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldIpa, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(fieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(fieldNama)
                            .addComponent(fieldPassword))))
                .addGap(13, 98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Username)
                    .addComponent(fieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaiIpa)
                    .addComponent(fieldIpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaiIps)
                    .addComponent(fieldIps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIndo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilaiIndo))
                .addGap(28, 28, 28)
                .addComponent(btnTambah)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
          username = fieldUsername.getText();
          password = fieldPassword.getText();
          nama = fieldNama.getText();
          status = "murid";
//          ipa = Integer.parseInt(fieldIpa.getText());
//          ips = Integer.parseInt(fieldIps.getText());
//          indo = Integer.parseInt(fieldIndo.getText());
//          if(username.equals(null)&&password.equals(null)&&nama.equals(null)&&fieldIpa.getText().equals(null)&&fieldIps.equals(null)&&fieldIndo.equals(null)){
//              JOptionPane.showMessageDialog(null,"Username wajib diisi");
//          }
        try{
            Controller.insert(username, password, nama, status, Integer.parseInt(fieldIpa.getText()), Integer.parseInt(fieldIps.getText()), Integer.parseInt(fieldIndo.getText()));
            Dosen dosen = new Dosen();
            dosen.setVisible(true);
            setVisible(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "Warning", JOptionPane.WARNING_MESSAGE);
        }
          
//          if (username.equals("")) {
//            JOptionPane.showMessageDialog(null, "Username wajib diisi !");
//        } else if (password.equals("")) {
//            JOptionPane.showMessageDialog(null, "Password wajib diisi !");
//        } else if (nama.equals("")) {
//            JOptionPane.showMessageDialog(null, "Nama wajib diisi !");
//        } else if (noHp.equals("")) {
//            JOptionPane.showMessageDialog(null, "No HP wajib diisi !");
//        } else if (alamat.equals("")) {
//            JOptionPane.showMessageDialog(null, "Alamat wajib diisi !");
//        } else {
//            Staff staff = new Staff(id, nama, noHp, alamat, id, username, password);
//            staffController.insert(staff);
//            initDataStaff();
//            resetFieldStaff();
//        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void fieldIpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIpsActionPerformed

    private void fieldIpaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIpaKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_fieldIpaKeyTyped

    private void fieldIpsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIpsKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_fieldIpsKeyTyped

    private void fieldIndoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIndoKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }//GEN-LAST:event_fieldIndoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField fieldIndo;
    private javax.swing.JTextField fieldIpa;
    private javax.swing.JTextField fieldIps;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel nilaiIndo;
    private javax.swing.JLabel nilaiIpa;
    private javax.swing.JLabel nilaiIps;
    // End of variables declaration//GEN-END:variables
}
